version: "3.4"

services:
  subyt.videosdb:
    image: mongo
    container_name: videosDb

    ports:
      - 27017:27017

    volumes:
      - ~/Documents/subyt/database:/data/db

    environment:
      - MONGO_INITDB_ROOT_USERNAME=randomUser
      - MONGO_INITDB_ROOT_PASSWORD=randomPassword
      - MONGO_INITDB_DATABASE=videosService

    networks:
      - mongoNetwork

    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh subyt.videosdb:27017 --quiet
      retries: 5
      interval: 5s
      start_period: 30s

  subyt.videosservice:
    image: videosservice
    container_name: videosService

    ports:
      - 3001:3001

    build:
      context: videosService

    environment:
      - PORT=3001
      - MONGO_URI=mongodb://randomUser:randomPassword@subyt.videosdb:27017
      - MONGO_DATABASE=videosService

    depends_on:
      subyt.videosdb:
        condition: service_healthy

    networks:
      - mongoNetwork

  subyt.ytservice:
    image: ytservice
    container_name: ytService

    build:
      context: ytService

    environment:
      - YOUTUBE_SEARCH_DEV_KEY=AIzaSyAIKdxKjTCEc6U45OZ5MTeVhhye2XtCJ9c
      - YOUTUBE_SEARCH_QUERY=RRR Oscar
      - SCHEDULER_SYNC_COOL_DOWN=30
      - SCHEDULER_REQUEST_COOL_DOWN=10
      - VIDEOS_SERVICE_URL=http://subyt.videosservice:3001

    networks:
      - mongoNetwork

    depends_on:
      subyt.videosdb:
        condition: service_healthy

    volumes:
      - /Users/varshneyabhushan/repos/subyt/ytService/checkPoint.json:/checkPoint.json
    


networks:
   mongoNetwork:
      name: mongo-network
      driver: bridge