version: "3.4"

services:
  subyt.videosdb:
    image: mongo
    container_name: videosDb

    ports:
      - $MONGO_PORT:27017

    volumes:
      - $MONGO_DATA_PATH:/data/db

    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_INITDB_ROOT_PASSWORD
      - MONGO_INITDB_DATABASE=$MONGO_INITDB_DATABASE

    networks:
      - mongoNetwork

    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh subyt.videosdb:27017 --quiet
      retries: 5
      interval: 5s
      start_period: 10s

  subyt.videosservice:
    image: videosservice
    container_name: videosService

    ports:
      - $VIDEOS_SERVICE_PORT:80

    build:
      context: videosService

    environment:
      - PORT=80
      - MONGO_URI=mongodb://$MONGO_INITDB_ROOT_USERNAME:$MONGO_INITDB_ROOT_PASSWORD@subyt.videosdb:27017
      - MONGO_DATABASE=$MONGO_INITDB_DATABASE
      - ELASTICSEARCH_URI=http://subyt.searchdb:9200

    depends_on:
      subyt.videosdb:
        condition: service_healthy

    networks:
      - mongoNetwork

  subyt.ytworker:
    image: ytworker
    container_name: ytWorker

    build:
      context: ytWorker

    environment:
      - YOUTUBE_SEARCH_DEV_KEY=$YOUTUBE_SEARCH_DEV_KEY
      - YOUTUBE_SEARCH_QUERY=$TOPIC
      - SCHEDULER_SYNC_COOL_DOWN=$SCHEDULER_SYNC_COOL_DOWN
      - SCHEDULER_REQUEST_COOL_DOWN=$SCHEDULER_SYNC_COOL_DOWN
      - VIDEOS_SERVICE_URL=http://subyt.videosservice
      - YOUTUBE_MAX_RESULTS=$YOUTUBE_MAX_RESULTS

    networks:
      - mongoNetwork

    depends_on:
      subyt.videosdb:
        condition: service_healthy

    volumes:
      - $YTWORKER_CHECKPOINT:/checkPoint.json

  subyt.searchdb:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.6.2
    container_name: searchDb

    ports:
      - $SEARCH_DB_PORT:9200

    volumes:
      - $SEARCH_DB_PATH:/usr/share/elasticsearch/data

    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node

    networks:
      - mongoNetwork


networks:
   mongoNetwork:
      name: mongo-network
      driver: bridge